
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 80 on the host to 3000 on this node
  extraPortMappings:  # FIXME: Force Node port ...
  - containerPort: 30000
    hostPort: 80
    protocol: TCP
