
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 80 on the host to 3000 on this node
  extraPortMappings:  # FIXME: Force Node port ...
  - containerPort: 30000
    hostPort: 8080
    protocol: TCP
  - containerPort: 30001
    hostPort: 8081
    protocol: TCP
  - containerPort: 30002
    hostPort: 8082
    protocol: TCP

