---
# Service
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: production
spec:
  selector:
    app: api
  ports:
  - port: 8082
    targetPort: 80
# - port: 443
#   targetPort: 443
    nodePort: 30002  # FIXME: Force Node port ...
  type: NodePort
  # type: LoadBalancer